--1. Cual es la cantidad de unidades de peliculas arrendadas desde el 24 de julio hasta el 24 de diciembre del 2005
SELECT SUM(FR.UNIDADES) AS cantidad_alquileres
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE (DT.ANNIO = 2005 AND DT.MES >= 7 AND DT.DIA >= 24)
   OR (DT.ANNIO = 2005 AND DT.MES = 12 AND DT.DIA <= 24);
	
-- 2. Cual fue la cantidad de unidades de peliculas arrendadas de la categoria "Family" durante el mes de julio de 2005?
SELECT 
	 DC.CATEGORIA AS CATEGORIA,
	 SUM(FR.UNIDADES) AS TOTAL_UNIDADES
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
WHERE DT.ANNIO = 2005
  AND DT.MES = 7
  AND DC.CATEGORIA = 'Family'
GROUP BY DC.CATEGORIA
ORDER BY SUM(FR.UNIDADES) DESC;

-- 3. Cuantas unidades de peliculas arrendadas con idioma ingles y de la categoria "games" se realizaron en la Tienda 1, en el mes julio del 2005
SELECT 
	DC.CATEGORIA AS CATEGORIA,
	DL.LENGUAJE AS LENGUAJE,
	SUM(FR.UNIDADES) AS TOTAL_UNIDADES
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_LENGUAJE DL ON FR.ID_LENGUAJE = DL.ID_LENGUAJE
WHERE DT.ANNIO = 2005
  AND DT.MES = 7
  AND DC.CATEGORIA = 'Games'
  AND DL.LENGUAJE = 'English'
  AND FR.ID_TIENDA = 1
GROUP BY DC.CATEGORIA, DL.LENGUAJE
ORDER BY SUM(FR.UNIDADES) DESC;

-- 4. Cantidad de unidades de peliculas arrendadas de la categoria "Horror" por tienda durante el mes de diciembre de 2004
SELECT FR.ID_TIENDA, SUM(FR.UNIDADES) AS Total_Unidades_Horror
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
WHERE DT.ANNIO = 2005
AND DC.CATEGORIA = 'Horror'
GROUP BY FR.ID_TIENDA;

-- 5. Cantidad de unidades de peliculas de la categoria "Music" en la Tienda 2, entre junio y agosto del 2005
SELECT 
	FR.ID_TIENDA AS TIENDA,
	DC.CATEGORIA AS CATEGORIA,
	DT. MES AS MES,
	DT.ANNIO AS ANNIO,
	SUM(FR.UNIDADES) AS Total_Unidades_Music
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
WHERE DT.ANNIO = 2005
  AND DT.MES BETWEEN 6 AND 8
  AND DC.CATEGORIA = 'Music'
  AND FR.ID_TIENDA = 2
GROUP BY FR.ID_TIENDA, CATEGORIA, MES, ANNIO;

-- 6. Cantidad de unidades de peliculas arrendadas de la categoria "Sports" en Argentina durante agosto de 2005
SELECT SUM(FR.UNIDADES) AS cantidad_alquileres
FROM FACT_RENTAL FR
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_DIRECCION DD ON FR.ID_DIRECCION = DD.ID_DIRECCION
WHERE DC.CATEGORIA = 'Sports'
  AND DD.PAIS = 'Argentina'
  AND FR.ID_TIEMPO BETWEEN '2005-08-01' AND '2005-08-31';

-- 7. Cantidad de unidades de peliculas arrendadas entre 2005 y 2006 con idioma italiano
SELECT SUM(FR.UNIDADES) AS Total_Unidades_Italiano
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_LENGUAJE DL ON FR.ID_LENGUAJE = DL.ID_LENGUAJE
WHERE DT.ANNIO IN (2005, 2006)
  AND DL.LENGUAJE = 'English';

-- 8. Peliculas arrendadas en 2005 con costo de reemplazo entre 15 y 25 dolares
SELECT SUM(FR.UNIDADES) AS Total_Peliculas
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_PELICULA DP ON FR.ID_PELICULA = DP.ID_FILM
WHERE DT.ANNIO = 2005
  AND DP.remplazar_costo BETWEEN 15 AND 25;

-- 9. Peliculas arrendadas en la tienda 1 en 2005 entre enero y septiembre
SELECT SUM(FR.UNIDADES) AS Total_Peliculas
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE DT.ANNIO = 2005
  AND DT.MES BETWEEN 1 AND 9
  AND FR.ID_TIENDA = 1;

-- 10. Monto total de ingresos por alquileres en Woodridge durante mayo de 2005
SELECT 
    SUM(FR.DINERO) AS total_ingresos
FROM 
    FACT_RENTAL FR
INNER JOIN 
    DIM_DIRECCION DD ON FR.ID_DIRECCION = DD.ID_DIRECCION
INNER JOIN 
    DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE 
    DD.CIUDAD = 'Woodridge'
    AND DT.ID_TIEMPO BETWEEN '2005-05-01' AND '2005-05-31';


-- 11. Cantidad promedio de dias de alquiler para peliculas de "Accion" de abril a junio de 2005
SELECT AVG(DATEDIFF(DAY, DT.ID_TIEMPO, DT2.ID_TIEMPO)) AS Promedio_Dias_Alquiler
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN FACT_RENTAL FR2 ON FR.ID_PELICULA = FR2.ID_PELICULA AND FR.ID_CLIENTE = FR2.ID_CLIENTE
JOIN DIM_TIEMPO DT2 ON FR2.ID_TIEMPO = DT2.ID_TIEMPO
WHERE DT.ANNIO = 2005
  AND DT.MES BETWEEN 4 AND 6
  AND DC.CATEGORIA = 'Action'
  AND DT2.ID_TIEMPO > DT.ID_TIEMPO;

-- 12. Categoria mas alquilada por clientes de idioma ingles en 2006
SELECT TOP 1 DC.CATEGORIA, COUNT(*) AS Total_Alquileres
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_LENGUAJE DL ON FR.ID_LENGUAJE = DL.ID_LENGUAJE
WHERE DT.ANNIO = 2006
  AND DL.LENGUAJE = 'English'
GROUP BY DC.CATEGORIA
ORDER BY Total_Alquileres DESC;

-- 13. Costo promedio de reemplazo de pel�culas alquiladas por clientes con m�s de 5 a�os de registro en 2005
SELECT AVG(DP.remplazar_costo) AS Promedio_Costo_Reemplazo
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CLIENTE DC ON FR.ID_CLIENTE = DC.ID_CLIENTE
JOIN DIM_PELICULA DP ON FR.ID_PELICULA = DP.ID_FILM
WHERE DT.ANNIO = 2005
  AND DATEDIFF(YEAR, DC.CREAR_DATOS, DT.ID_TIEMPO) > 5;

-- 14. Top 5 clientes con mayores ingresos por alquiler entre 2005 y 2006
SELECT TOP 5 DC.ID_CLIENTE, DC.NOMBRE, DC.APELLIDO, SUM(FR.DINERO) AS Total_Ingresos
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CLIENTE DC ON FR.ID_CLIENTE = DC.ID_CLIENTE
WHERE DT.ANNIO IN (2005, 2006)
GROUP BY DC.ID_CLIENTE, DC.NOMBRE, DC.APELLIDO
ORDER BY Total_Ingresos DESC;

-- 15. Ingreso total por alquileres de pel�culas de "Aventura" en la tienda 2 durante 2005
SELECT SUM(FR.DINERO) AS ingreso_total
FROM FACT_RENTAL FR
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE DC.CATEGORIA = 'Horror'
  AND FR.ID_TIENDA = 2
  AND DT.ANNIO = 2005;

-- 16. Ingreso total por alquileres de todas las pel�culas en la tienda 2 durante 2005
SELECT SUM(FR.DINERO) AS Total_Ingresos
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE DT.ANNIO = 2005
  AND FR.ID_TIENDA = 2;

-- 17. Unidades de pel�culas alquiladas a clientes con m�s de 1 a�o de registro durante 2005
SELECT SUM(FR.UNIDADES) AS cantidad_unidades
FROM FACT_RENTAL FR
JOIN DIM_CLIENTE DC ON FR.ID_CLIENTE = DC.ID_CLIENTE
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE DATEDIFF(YEAR, DC.CREAR_DATOS, GETDATE()) > 1
  AND DT.ANNIO = 2005;

-- 18. Unidades de pel�culas de "Animaci�n" alquiladas por clientes de habla japonesa en 2005
SELECT SUM(FR.UNIDADES) AS Total_Unidades_Animacion_Japones
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_LENGUAJE DL ON FR.ID_LENGUAJE = DL.ID_LENGUAJE
WHERE DT.ANNIO = 2005
  AND DC.CATEGORIA = 'Animation'
  AND DL.LENGUAJE = 'English';

-- 19. Ingreso total por arriendos de pel�culas de "Viajes" en la tienda 1 durante el 2005 y 2006
SELECT SUM(FR.DINERO) AS Total_Ingresos_Viajes
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
WHERE DT.ANNIO = 2005
  AND DC.CATEGORIA = 'Travel'
  AND FR.ID_TIENDA = 1;

-- 20. Cantidad de unidades de pel�culas arrendadas por d�a durante mayo de 2005
SELECT DT.ID_TIEMPO, SUM(FR.UNIDADES) AS Total_Unidades
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
WHERE DT.ANNIO = 2005
  AND DT.MES = 5
GROUP BY DT.ID_TIEMPO
ORDER BY DT.ID_TIEMPO;

-- 21. Total de ingresos por arriendos de pel�culas de "Acci�n" en Rashunka, Zambia, durante los primeros 3 meses de 2005
SELECT SUM(FR.DINERO) AS Total_Ingresos_Accion
FROM FACT_RENTAL FR
JOIN DIM_TIEMPO DT ON FR.ID_TIEMPO = DT.ID_TIEMPO
JOIN DIM_CATEGORIA DC ON FR.ID_CATEGORIA = DC.ID_CATEGORIA
JOIN DIM_DIRECCION DD ON FR.ID_DIRECCION = DD.ID_DIRECCION
WHERE DT.ANNIO = 2005
  AND DT.MES BETWEEN 1 AND 3
  AND DC.CATEGORIA = 'Action'
  AND DD.CIUDAD = 'Rashunka'
  AND DD.PAIS = 'Zambia';